// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBpLo8ZZMNl8TizdInaMpCsZ8cCxtLiVE',
    appId: '1:163340677850:web:c1a6610081860637352be3',
    messagingSenderId: '163340677850',
    projectId: 'benjii-project',
    authDomain: 'benjii-project.firebaseapp.com',
    storageBucket: 'benjii-project.firebasestorage.app',
    measurementId: 'G-LC3YSKQ7Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiswC7Grve_4MwWmGXYqizEjrfO1aLU0s',
    appId: '1:163340677850:android:00929c77b5fd389d352be3',
    messagingSenderId: '163340677850',
    projectId: 'benjii-project',
    storageBucket: 'benjii-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMuEcasm9DWFUb0DmZHnAt-9ZyagpyrNY',
    appId: '1:163340677850:ios:d4227815d20896d0352be3',
    messagingSenderId: '163340677850',
    projectId: 'benjii-project',
    storageBucket: 'benjii-project.firebasestorage.app',
    iosBundleId: 'com.example.benjii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMuEcasm9DWFUb0DmZHnAt-9ZyagpyrNY',
    appId: '1:163340677850:ios:d4227815d20896d0352be3',
    messagingSenderId: '163340677850',
    projectId: 'benjii-project',
    storageBucket: 'benjii-project.firebasestorage.app',
    iosBundleId: 'com.example.benjii',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBpLo8ZZMNl8TizdInaMpCsZ8cCxtLiVE',
    appId: '1:163340677850:web:e950f4db31e49a85352be3',
    messagingSenderId: '163340677850',
    projectId: 'benjii-project',
    authDomain: 'benjii-project.firebaseapp.com',
    storageBucket: 'benjii-project.firebasestorage.app',
    measurementId: 'G-8L9ZDGFSRR',
  );
}
